### PR TITLE
add argument for allow_missing in check_dates

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by erikarasnick** [comment]
@cole-brokamp Not sure how to print the name of the offending column as we discussed... `check_dates` just takes a vector of dates.

**Comment by cole-brokamp** [comment]
OK, let me take a look and think about it before we talk tomorrow

**Comment by cole-brokamp** [comment]
@erikarasnick - we can merge this; printing name of offending column is not needed

**Comment by erikarasnick** [comment]
@cole-brokamp okay. Do you think we should up this from 0.4.2 to 0.4.3 ?

**Comment by cole-brokamp** [comment]
We are undergoing such rapid development here, I think I will merge in these two PRs and then up the version.

**Pull request merged**
