### PR TITLE
create pkgdown site with vignettes

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by cole-brokamp** [comment]
this is great!  check out what I added in and go ahead and merge.

**Comment by erikarasnick** [comment]
I can't get bootstrap 5 to work for me locally. I get this error: 

`Error : Didn't recognize Bootstrap version: 5   
Error: callr subprocess failed: Didn't recognize Bootstrap version: 5`

Do you think I need to update bootstrap? I looked into this a bit yesterday, but couldn't find much.

**Comment by cole-brokamp** [comment]
Did you install the latest version of {pkgdown}?

**Comment by erikarasnick** [comment]
yes I have pkgdown 2.0.1

**Comment by cole-brokamp** [comment]
maybe its looking for bootstrap 5 in the folders where bootstrap 3 was installed when building the site locally with an older version of {pkgdown}.  try removing all the files created by {pkgdown} and then building the site?

**Comment by erikarasnick** [comment]
If I remove the _pkgdown.yaml file the site will build, but then I'm not sure if it's using bootstrap 3 or 5.

**Comment by cole-brokamp** [comment]
I mean removing everything under `docs` folder where it builds the sites.  It also "installs" bootstrap there by copying it from the internet.  I think it only happens when needed and could be where bootstrap 3/5 are getting mixed up?

**Comment by erikarasnick** [comment]
Oh, I think I tried that yesterday. But I just tried it again and I get the same error.

**Comment by cole-brokamp** [comment]
I'll merge it and if it doesn't work will revert it right away.

**Comment by cole-brokamp** [comment]
its working !  

i looked into your error too and found absolutely nothing as well....

**Comment by erikarasnick** [comment]
that's weird but glad it's working!

**Pull request merged**
