### PR TITLE
suggest sf instead of requiring

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by erikarasnick** [comment]
@cole-brokamp checks fail here because sf is suggested but not available

**Comment by cole-brokamp** [comment]
And it only happens on mac and windows... Can we set the check to not error on a missing suggested package by following the suggestion here? https://github.com/degauss-org/dht/pull/14/checks?check_run_id=3011142599#step:9:40

**Comment by erikarasnick** [comment]
Seems to be working. Now just tests that require sf fail

**Comment by cole-brokamp** [comment]
I guess we should skip those tests if sf is not available.

**Comment by cole-brokamp** [comment]
I figured the windows fail was a CI glitch and I reran the checks, but still fails... I think we can accept and merge anyway.

**Pull request merged**
