### PR TITLE
check_ram

### PR DESCRIPTION
**Pull request by cole-brokamp**
This adds a check_ram function, which will send a message to a DeGAUSS user if the GB of RAM available is less than is recommended.

### CODE REVIEW

**Comment by cole-brokamp** [comment]
closes #33

**Comment by cole-brokamp** [comment]
@erikarasnick, can you test this inside a working container?  not sure the best way to go about it, but maybe set the threshold really high and expect a warning message when you run something locally?

**Comment by erikarasnick** [comment]
Screen Shot 2021-11-22 at 3 36 20 PM

Seems like it's working! I have my Docker RAM set to 10 GB. This is in the PM container, for reference.

**Comment by cole-brokamp** [comment]
Yes!!  Our first step to robot troubleshooting 😄 thanks!

**Pull request merged**
